---
name: fastapi-application-ci-pipeline

on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  testing-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linters
        run: |
          flake8 .
          black --check .
  unit-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run unit tests
          run: |
            echo "Running unit tests..."
  build-docker-image:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref_type == 'tag'
        needs: 
            - testing-ci
            - unit-test
        steps:
          - name: Extract version from tag
            uses: docker/metadata-action@v5
            id: meta
            with:
                images: |
                    ${{ vars.DOCKERHUB_USERNAME }}/fastapi-application-ci
                tags: |
                    type=semver,pattern={{version}}
                    type=sha,pattern={{sha}}å
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and push Docker image
            uses: docker/build-push-action@v6
            env:
                DOCKER_BUILD_SUMMARY: false
            with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
